// src/app/_components/testimonials.tsx
"use client";
import { useEffect, useRef, useState } from "react";

const Testimonials = () => {
  const testimonialsRef = useRef<HTMLDivElement | null>(null);
  const [activeIndex, setActiveIndex] = useState(0);

  const testimonialList = [
    {
      title: `"Zero8 got our MVP up and running in virtually no time."`,
      author: "Vex Lexter, Aerotropic",
    },
    {
      title: `"Zero8 got our MVP up and running in virtually no time."`,
      author: "Vex Lexter, Aerotropic",
    },
    {
      title: `“Could not have deployed our vision better or sooner without Zero8.”`,
      author: "Wren Tedder, Navajo",
    },
  ];

  const handleScroll = () => {
    if (testimonialsRef.current) {
      const scrollLeft = testimonialsRef.current.scrollLeft;
      const width = testimonialsRef.current.offsetWidth;
      const index = Math.round(scrollLeft / width);
      setActiveIndex(index);
    }
  };

  const scrollToIndex = (index: number) => {
    if (testimonialsRef.current) {
      testimonialsRef.current.scrollTo({
        left: index * testimonialsRef.current.offsetWidth,
        behavior: "smooth",
      });
    }
  };

  useEffect(() => {
    const ref = testimonialsRef.current;
    if (ref) {
      ref.addEventListener("scroll", handleScroll);
    }
    return () => {
      if (ref) {
        ref.removeEventListener("scroll", handleScroll);
      }
    };
  }, []);

  return (
    <section className="mb-4 col-span-1 h-auto" aria-label="Testimonials">
      <h2 className="sr-only">Testimonials</h2>{" "}
      <div
        className="font-extralight flex w-full overflow-x-hidden snap-x 
          snap-mandatory lg:grid lg:grid-cols-3 lg:gap-x-4"
        ref={testimonialsRef}
        role="region"
        aria-label="Customer testimonials carousel"
      >
        {testimonialList.map((testimonial, index) => (
          <article
            key={index}
            className="min-w-full p-2 h-56 bg-charcoal rounded text-description 
              text-base lg:text-xl flex flex-col justify-center items-center 
              snap-center lg:p-4"
          >
            <blockquote>
              <p>{testimonial.title}</p>
            </blockquote>
            <cite className="text-base text-right">- {testimonial.author}</cite>
          </article>
        ))}
      </div>
      <div className="flex justify-center gap-x-2 my-2 lg:hidden">
        {testimonialList.map((_, index) => (
          <button
            key={index}
            className={`w-4 h-4 rounded-full ${
              index === activeIndex ? "bg-red-500" : "bg-description"
            } cursor-pointer`}
            aria-label={`Go to testimonial ${index + 1}`}
            onClick={() => scrollToIndex(index)}
          />
        ))}
      </div>
    </section>
  );
};

export default Testimonials;

// src/lib/components/sections/Testimonials.svelte
<script lang="ts">
	import { testimonials } from '$lib/data/site';
	import { onMount } from 'svelte';

	let carouselEl: HTMLDivElement;
	let activeIndex = $state(0);

	function handleScroll() {
		if (!carouselEl) return;
		const index = Math.round(carouselEl.scrollLeft / carouselEl.offsetWidth);
		activeIndex = index;
	}

	function scrollToIndex(index: number) {
		if (!carouselEl) return;
		carouselEl.scrollTo({ left: index * carouselEl.offsetWidth, behavior: 'smooth' });
	}

	onMount(() => {
		carouselEl.addEventListener('scroll', handleScroll, { passive: true });
		return () => carouselEl.removeEventListener('scroll', handleScroll);
	});
</script>

<section class="testimonials col-full" aria-label="Testimonials">
	<h2 class="sr-only">Testimonials</h2>
	<div class="carousel" bind:this={carouselEl} role="region" aria-label="Customer testimonials">
		{#each testimonials as t, i}
			<article class="card" aria-label="Testimonial {i + 1}">
				<blockquote>
					<p class="quote">{t.quote}</p>
				</blockquote>
				<cite class="author">— {t.author}</cite>
			</article>
		{/each}
	</div>

	<!-- Mobile dots -->
	<div class="dots" role="tablist" aria-label="Testimonial navigation">
		{#each testimonials as _, i}
			<button
				class="dot"
				class:active={i === activeIndex}
				onclick={() => scrollToIndex(i)}
				aria-label="Go to testimonial {i + 1}"
				aria-selected={i === activeIndex}
				role="tab"
			></button>
		{/each}
	</div>
</section>

<style>
	.sr-only {
		position: absolute;
		width: 1px;
		height: 1px;
		padding: 0;
		margin: -1px;
		overflow: hidden;
		clip: rect(0, 0, 0, 0);
		white-space: nowrap;
		border: 0;
	}

	.carousel {
		display: flex;
		overflow-x: auto;
		scroll-snap-type: x mandatory;
		scroll-behavior: smooth;
		-webkit-overflow-scrolling: touch;
		gap: 16px;
		scrollbar-width: none;
	}

	.carousel::-webkit-scrollbar {
		display: none;
	}

	@media (min-width: 1024px) {
		.carousel {
			display: grid;
			grid-template-columns: repeat(3, 1fr);
			overflow: visible;
		}
	}

	.card {
		min-width: 100%;
		flex-shrink: 0;
		scroll-snap-align: center;
		background: var(--color-charcoal);
		border-radius: 4px;
		padding: 16px;
		height: 224px;
		display: flex;
		flex-direction: column;
		justify-content: center;
		align-items: center;
		gap: 12px;
		color: rgba(237, 237, 237, 0.7);
	}

	@media (min-width: 1024px) {
		.card {
			min-width: unset;
			padding: 24px;
			font-size: 20px;
		}
	}

	.quote {
		text-align: center;
		font-size: clamp(14px, 1.5vw, 20px);
	}

	.author {
		font-style: normal;
		font-size: clamp(12px, 1.2vw, 16px);
		align-self: flex-end;
	}

	.dots {
		display: flex;
		justify-content: center;
		gap: 8px;
		margin-top: 16px;
	}

	@media (min-width: 1024px) {
		.dots {
			display: none;
		}
	}

	.dot {
		width: 16px;
		height: 16px;
		border-radius: 50%;
		border: none;
		cursor: pointer;
		background: var(--color-description);
		transition: background 0.2s;
	}

	.dot.active {
		background: var(--color-icon-green);
	}
</style>
